author: Denys Telezhkin
author_url: https://github.com/DenTelezhkin
github_url: https://github.com/DenTelezhkin/Ariadne
root_url: https://dentelezhkin.github.io/Ariadne/
module: Ariadne
xcodebuild_arguments: [-scheme, Ariadne, -sdk, iphonesimulator]
output: docs
theme: fullwidth
