sudo: false
language: objective-c
os: osx
osx_image: xcode11.1

matrix:
  include:
    - env: ACTION=test_ios13 PLATFORM=iOS
    # - env: ACTION=test_ios12 PLATFORM=iOS
    - env: ACTION=test_tvos13 PLATFORM=tvOS
    # - env: ACTION=test_tvos12 PLATFORM=tvOS
    - env: ACTION=test_macos PLATFORM=macOS
    - env: ACTION=build_watchos PLATFORM=watchOS
    - env: ACTION=pod_lint PLATFORM=iOS
    - env: ACTION=carthage_build PLATFORM=iOS
before_install:
  - gem update --system
  - gem install bundler
script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION
