name: "CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Xcode-12:
    name: Xcode 12
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios14", "test_tvos14","test_macos", "build_watchos_xcode12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: List simulators
        run: instruments -s devices
      - name: ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  Xcode-11:
    name: Xcode 11
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios13", "test_tvos13","test_macos", "build_watchos"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: List simulators
        run: instruments -s devices
      - name: ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  cocoapods:
    name: Lint podspec
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: CocoaPods spec lint
        run: bundle exec fastlane pod_lint
