name: "CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  iOS-Xcode-12:
    name: Xcode 12 iOS 14
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios14"] #,"test_ios12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: List simulators
        run: instruments -s devices
      - name: iOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  tvOS-Xcode-12:
    name: Xcode 12 tvOS 14
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_tvos14"] #,"test_tvos12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: tvOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  macOS-Xcode12:
    name: Xcode 12 macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: macOS
        run: bundle exec fastlane test_macos
  macOS:
    name: macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: macOS
        run: bundle exec fastlane test_macos
  iOS:
    name: Xcode 11 iOS 13
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios13"] #,"test_ios12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: List simulators
        run: instruments -s devices
      - name: iOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  tvOS:
    name: Xcode 11 tvOS 13
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_tvos13"] #,"test_tvos12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: tvOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  watchOS:
    name: Xcode 11 watchOS 6
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: watchOS - ${{ matrix.destination }}
        run: bundle exec fastlane build_watchos
  watchOS-Xcode12:
    name: Xcode 12 watchOS 7
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: watchOS - ${{ matrix.destination }}
        run: bundle exec fastlane build_watchos_xcode12
  cocoapods:
    name: Lint podspec
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: CocoaPods spec lint
        run: bundle exec fastlane pod_lint
